# Generated by Django 3.2 on 2021-04-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rank_search',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('product_name', models.CharField(db_column='product_name', max_length=20)),
                ('total_rank', models.IntegerField(db_column='total_rank')),
                ('date', models.CharField(db_column='date', max_length=20)),
                ('keyword', models.CharField(db_column='keyword', max_length=20)),
            ],
            options={
                'db_table': 'rank_search',
                'managed': False,
            },
        ),
    ]
